### ISSUE TITLE
Изменение времени обрабоки

### ISSUE THREAD

**Issue by Valetron** [myaak/new-camera-controller#6]
При изменении значения интервала обработки в поле пишется NaN и не получается изменить это поле.
![image](https://user-images.githubusercontent.com/43819843/236578151-d2d06593-8a58-458e-a2e0-d08277b080fa.png)

**Comment by myaak** [comment]
Доброе утро, коллега. Сегодня исправим для вашего комфортного пользования

**Comment by Valetron** [comment]
Данная ошибка появляется только при отсуствии камер, при наличии хотя бы одной камеры, данная ошибка не появляется.
![image](https://user-images.githubusercontent.com/43819843/236579231-53c8e43b-2b10-4dca-b365-7c4acba49b4b.png)

**Comment by myaak** [comment]
> Данная ошибка появляется только при отсуствии камер, при наличии хотя бы одной камеры, данная ошибка не появляется. ![image](https://user-images.githubusercontent.com/43819843/236579231-53c8e43b-2b10-4dca-b365-7c4acba49b4b.png)

Проверяйте, коллега. Исправил ошибку с NaN

**Comment by myaak** [comment]
Все исправлено
